[package]
name = "comms-project"
version = "0.1.0"
edition = "2024"

[dependencies]
[target.'cfg(any(target_arch = "arm", target_arch = "aarch64"))'.dependencies]
rppal = "0.22.1"

[target.arm-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"